### ISSUE TITLE
Provide functional React.js component example

### ISSUE THREAD

**Issue by n1ru4l** [wavesoft/dot-dom#23]
It would be nice to add a functional react.js component example (https://github.com/wavesoft/dot-dom#2-simple-component)

The example would be much shorter than the class example.
If you are okay with this I would submti a pull request

**Comment by wavesoft** [comment]
That's a good idea @n1ru4l ! If you could create a PR that would be great 👍

**Comment by n1ru4l** [comment]
By adding the example there would be some horizontal scrolling which looks ugly to me. Would you be okay with removing the other React example? For me it seems strange to compare the react class engine with dot-doms functional engine

**Comment by styfle** [comment]
I agree, the React example should just be a stateless component.

```js
function Hello(props) {
    return React.createElement(
      'div', null, `Hello ${props.toWhat}`
    );
  }
```

**Comment by styfle** [comment]
I created PR #24

**Comment by wavesoft** [comment]
As @styfle pointed out, the `Stateless Component` can actually use the functional javascript component. However, the `Stateful Component` still needs a class in React. 

However we could have gone with `React.createClass` instead of extending the `Component` class, but I think the latter is a bit cleaner.

**Comment by wavesoft** [comment]
I will keep this issue open for a while just in case @n1ru4l wants to do any addition. Otherwise I will close it soon.

**Comment by n1ru4l** [comment]
I would have done the same as @styfle :+1: 
Nothing to add!
