### ISSUE TITLE
Feature: add module.exports...

### ISSUE THREAD

**Issue by SilentCicero** [wavesoft/dot-dom#4]
In order for me to use this at all I have to use global, which means I need to transpile that down. It's not nice. Please add `module.exports` somewhere here so I can actually use this node without global.

At least module.exports the main function. I'm fine if you auto apply it globally, I would just prefer I can setup my own globals and submethods.

**Comment by wavesoft** [comment]
Hey @SilentCicero you are actually right, I haven't spend enough time making it more npm friendly. Will definitely fix this ASAP

**Comment by wavesoft** [comment]
Hey @SilentCicero , #19 should have fixed this issue 👍  If not, feel free to re-open it!
