### ISSUE TITLE
Does not work well with spreads

### ISSUE THREAD

**Issue by SilentCicero** [wavesoft/dot-dom#5]
This doesn't seem to be possible:

```js
function createElement(tag, props, children) {
  return global.H(tag, props, ...children);
}
```

The result:

```
Object {E: "apply", P: Window, Symbol(): 1}
E:
"apply"
P:
Window
Symbol():
1
__proto__:
Object
```

It is assuming apply is a component, when it is not.

**Comment by wavesoft** [comment]
Hello @SilentCicero and thank you for your comments. I bet you are using babel, right?

This is not really an issue with the spread itself, but with the transformation since it becomes `H.apply (this, [].concat (tag, props, children)` and therefore becomes a tag shorthand syntax.

This library is not really meant to be used with babel polyfills.

**Comment by SilentCicero** [comment]
Right, I understand, but I think you should maybe offer a npm/babel way to benefit from this module. We dont want this hard work to go to waste on just IoT devices.

**Comment by SilentCicero** [comment]
Can you give an example or way for me to do this without babel transform spread operator?

**Comment by wavesoft** [comment]
I will actually create an NPM polyfil module that implements some of the functionality needed in order to integrate this with babel 👍

**Comment by wavesoft** [comment]
What would that do is prohibit `apply` from being forwarded to the `Proxy` object 😄

**Comment by SilentCicero** [comment]
Why dont you just restrict apply conditionally. That way we can just use spreads properly.

**Comment by wavesoft** [comment]
@SilentCicero I wanted to keep the library core intact and build around the existing structures - if possible.

This is now related to #4 and the general "npm-ization" process of the library so I am going to close this issue.
