### ISSUE TITLE
Unused variable _reserved

### ISSUE THREAD

**Issue by mindplay-dk** [wavesoft/dot-dom#59]
Looks like there's an unused variable `_reserved` in `render()`.

I think you can scrap that and save 2 bytes?

Not sure, `terser` might be detecting it and removing it already, but it's unused either way.

**Comment by wavesoft** [comment]
Not really 😉 

This `_reserved` argument is the third to the `map` callback. It will be populated with the reference of the array. This means that it _will_ have a value, and the initialisation trick won't work. ([Check MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Parameters) for more details)

I tried using this variable as a temporary storage, but apparently it ended up increasing the compressed result.

**Comment by mindplay-dk** [comment]
Ah, so this is just a throw-away variable so you can abuse the unused arguments as a shorthand to define variables, gotcha 😉
