### ISSUE TITLE
Extra space in keys? [0.4.0]

### ISSUE THREAD

**Issue by mindplay-dk** [wavesoft/dot-dom#61]
Why the extra space in the key-name here?

https://github.com/wavesoft/dot-dom/blob/ddd6d50f9609b97f79ee9af10387598cfa19e7a5/src/dotdom.js#L197

If it's just for type-coercion, an empty string should work just as well?

**Comment by wavesoft** [comment]
Yeah, this is for type-coercion *and* compression optimisation : repeating patterns 😉 

Since you don't really care about _what_ the automatic key really contains, it should be fine

**Comment by mindplay-dk** [comment]
So if I understand this correctly, you're using the extra space because you've used the same `" "` sequence in a few other places, and this compresses better??

I think you just blew my mind LOL 🤯
