### ISSUE TITLE
What's the 512b magic number?

### ISSUE THREAD

**Issue by osdevisnot** [wavesoft/dot-dom#62]
This is mostly a question, but I was wondering what's so special about 512b number? Looking at some of the open/closed issues it seems you are attempting to fit an entire website (lib + css + app) in the MTU size (usually 1500 bytes). But I have no idea about iot devices, and I'm trying to figure implications of exceeding 1500 bytes.

Any pointers that can help me wrapping my head around the size limitations?

**Comment by wavesoft** [comment]
Hello @osdevisnot !

Yes this indeed a _magic_ number... but it's purpose is two-fold: 

## 1. It just as small as it has to be

First of all, start by having a look on the specs of an average device that could be used for IoT. For example to the [ARDUINO MKR1000 WIFI](https://store.arduino.cc/arduino-mkr1000-wifi). You will notice on the tech specs that it says:

> Flash Memory | 256 KB

Most of the MCUs in the market don't have a much bigger flash size, and don't forget that this size includes the bootloader, C/C++ libraries, a web server and your business logic in **addition** to the static files for the static UI you want to serve.

This means that you should optimise things as much as physically possible. Ideally, your entire UI must fit in less than a KB!

With this in mind, I started sketching out possible implementations of the library and aimed to fit it in the smallest power of 2 that I could reach. Interestingly enough, in around 400-500 bytes (Gzipped) I managed to squeeze all of the logic that could satisfy my demands. 

So the closest power of 2 was **512 bytes**, giving me some slack for future features.

## 2. It is a contract

After setting on that number, I decided to make this a contract, and lock this library to it. Even though it sounds controversial, this has quite some benefits:

  1. Embedded system designers are very cautious with the size of their solution, and having a library with consistent size is a big plus.

  1. Developing under a size constraint made me pay more attention to the code-base, and made me realise that it's possible to add more features in a code-base without increasing it's size.

  1. So far this the smallest library in the market with this feature-set, and I would like to keep it this way.

However I am still willing to break this contract if there is a powerful feature that the community will desire 😄

**Comment by wavesoft** [comment]
Also, the "Fitting into an MTU" exercise was just a demonstration on how small you can really make things. 

In a more real-world examples, I have already developed a few user interfaces for such IoT devices using **.dom** :

1. A configuration user interface that is mobile-first, responsive and has 15 different widgets.
    <img width="450" src="https://user-images.githubusercontent.com/883486/69585990-8b754c80-0fe1-11ea-992a-3adc8a93882a.png" />

2. A javascript code editor with syntax highlight
    <img width="450" src="https://user-images.githubusercontent.com/883486/69586282-659c7780-0fe2-11ea-97d6-e02e7ab65b5a.png" />

3. A log-viewing user interface that can render and live-filter gigabytes of log lines (using virtual viewport)

Each one of these interfaces is about **3.5Kb** in size (js, css, html and all other assets included)
