### ISSUE TITLE
IoT Device targets?

### ISSUE THREAD

**Issue by SilentCicero** [wavesoft/dot-dom#7]
What IoT device runs JS and requires this small a package size? Just curious.

**Comment by wavesoft** [comment]
This is not for running **in** IoT devices, but rather to be used as a library when serving Web GUIs from IoT devices.

Nonetheless there are frameworks such as http://johnny-five.io if you want to actually run js

**Comment by wavesoft** [comment]
But you have a point. I might need to adjust a bit the description :smile:

**Comment by wavesoft** [comment]
I am going to close this since it's not an issue 👍
